remote_theme: mmistakes/minimal-mistakes
title: "MoMaF home"
description: "The Movie Making Finland Project"


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
