remote_theme: mmistakes/minimal-mistakes
title: "Movie Making Finland: Finnish fiction films as audiovisual big data, 1907–2017 (MoMaF)"
name: "MoMaF"
description: "Movie Making Finland: Finnish fiction films as audiovisual big data, 1907–2017 (MoMaF)"
locale: "en-GB"
url: https://momaf.github.io
baseurl: ""
repository: momaf/momaf.github.io
breadcrumbs: true
logo: "/assets/images/camera_88.png"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
